"""
Django settings for yatube project.

Generated by 'django-admin startproject' using Django 2.2.19.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@og3kshb!3(-_&v3!$e$9izo)gk(@cywd@^ocb84!=r263$3lv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # Добавлено: для прода False

ALLOWED_HOSTS = []
# Добавлено: для прода
# ALLOWED_HOSTS = [
#     'localhost',
#     '127.0.0.1',
#     '[::1]',
#     'testserver', ]

# Application definition

INSTALLED_APPS = [
    'core.apps.CoreConfig',
    'users.apps.UsersConfig',  # Добвлено: добавили приложение users
    'posts.apps.PostsConfig',  # Добвлено: добавили приложение posts (apps.py -> PostsConfig)
    'django.contrib.admin',
    'django.contrib.auth',  # Добвлено: по умолчанию создается автоматическая работа пользователя со своим аккаунтом
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'sorl.thumbnail',  # Добвлено: добавили библиотеку для работы с картинками
    'rest_framework',  # Добвлено: зависимость для работы с Django Rest API
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'yatube.urls'

# Добвлено: путь, где хранятся статические данные (изображения, стили css и т.д.)
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)

# Добвлено: путь, куда сохранять загруженные фото для постов пользователя
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Добвлено: путь, где хранятся шаблоны
TEMPLATES_DIR = os.path.join(BASE_DIR, 'templates')

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Добавлено: Искать шаблоны на уровне проекта
        'DIRS': [TEMPLATES_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Добавлено: конеткст-процессор - общие переменных для html шаблонов
                'core.context_processors.year.year'
            ]
        },
    }
]

WSGI_APPLICATION = 'yatube.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

# Добавлено: если происходят какие-то изменения в моделях БД, в консоли пишем:
# python manage.py makemigrations
# python manage.py migrate

# Создаём администратора: python manage.py createsuperuser
# Username: alika
# Email address: minackowa.ali@yandex.ru
# Password: yfz-HJA-ksc-q6E

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = "ru"  # Добавлено: изменили язык на русский

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Добавлено: куда перенаправить пользователя после успешной или нет авторизации
LOGIN_URL = 'users:login'
LOGIN_REDIRECT_URL = 'posts:index'
# LOGOUT_REDIRECT_URL = 'posts:index'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

# Добавлено: для эмуляции почтового ящика в консоли при сбросе пароля
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

handler404 = 'core.views.page_not_found'  # Добавлено: где обрабатывать ошибки 404
CSRF_FAILURE_VIEW = 'core.views.csrf_failure'  # Добавлено: где обрабатывать ошибки отсутствия csrf токена

# Добавлено: прописываем путь для хранения картинок
DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

